### ISSUE TITLE
Investigate using Rayon for delegation storage

### ISSUE THREAD

**Issue by dopatraman** [LibertyDSNP/mrc#130]
Currently we iterate sequentially over delegation ids before checking their delegation statuses. Let's investigate using Rayon's parallel iterators for this.

**Comment by aramikm** [comment]
We can probably do this by pulling out the iteration logic into RPC which can be use std libraries

**Comment by saraswatpuneet** [comment]
Agreed with Aramik we should keep logic away from runtime
