### ISSUE TITLE
[Question] How to create signature proof for Msa functions

### ISSUE THREAD

**Issue by iamianM** [LibertyDSNP/mrc#146]
Hi I cannot get verification to pass for creating a signature from a payload using substrate in python. My code is below. Any help would be greatly appreciated, thank you.
```
def make_call(call_module, call_function, call_params, keypair):
    call = substrate.compose_call(
        call_module=call_module,
        call_function=call_function,
        call_params=call_params
    )

    extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)
    
alice = Keypair.create_from_uri('//Alice')
make_call("Msa", "create", {}, alice)
# encode payload with 
payload_raw = { "msa_id": 3, "nonce": 0 }
add_provider_payload = substrate.encode_scale(type_string='scale_info::8', value=payload_raw['msa_id']) + substrate.encode_scale(type_string='scale_info::4', value=payload_raw['nonce'])
signature = alice.sign(add_provider_payload).hex()
call_params = {
    "key": alice.ss58_address,
    "proof": {"Sr25519": "0x" + signature.hex()},
    "add_key_payload": payload_raw
}
make_call("Msa", "add_key_to_msa", call_params, alice)
```
I get the error 

> {'type': 'Module',
 'name': 'AddKeySignatureVerificationFailed',
 'docs': ['Cryptographic signature verification failed for adding a key to MSA']}

**Comment by enddynayn** [comment]
Hi @iamian

I notice that add_provider_payload is not being wrapped with <bytes></bytes>. You can take a look at the test example below. We do this because this is what the wallet does when you sign a message with it. 

https://github.com/LibertyDSNP/mrc/blob/main/pallets/msa/src/tests.rs#L202
https://github.com/LibertyDSNP/mrc/blob/main/common/primitives/src/utils.rs#L38
https://github.com/LibertyDSNP/mrc/blob/main/pallets/msa/src/lib.rs#L383

**Comment by iamianM** [comment]
@enddynayn Thanks for the reply.

I tried 
```
add_provider_payload = substrate.encode_scale(type_string='str', value="<Bytes>") + substrate.encode_scale(type_string='scale_info::8', value=payload_raw['msa_id']) + substrate.encode_scale(type_string='scale_info::4', value=payload_raw['nonce']) + substrate.encode_scale(type_string='str', value="</Bytes>")
```
and
```
add_provider_payload = "<Bytes>".encode() + add_provider_payload.data + "</Bytes>".encode()
```
but no luck.

**Comment by enddynayn** [comment]
@iamianM in your call_params instead of using ss58_address can you try the public key hex instead.

**Comment by iamianM** [comment]
Hey @enddynayn, so I ran through all attempts and managed to get a new error using this method to get the payload `"<Bytes>".encode() + add_provider_payload.data + "</Bytes>".encode()`

> {'type': 'Module', 'name': 'DuplicatedKey', 'docs': ['tried to add a key that was already registered']}

Which I guess means the key was registered during the `create` function?
Either way I figured that resolved the signature issue so I tried to run the `add_provider_to_msa` function, but am back to the old error

> {'type': 'Module', 'name': 'AddProviderSignatureVerificationFailed', 'docs': ['Cryptographic signature verification failed for adding the Provider as delegate']}

Here is my notebook https://github.com/iamianM/PostThread-Polkadot/blob/main/reddit-reposter/create-MSA.ipynb
You can scroll to the bottom for the errors.
Thank you for the help.

**Comment by iamianM** [comment]
I managed to get it to work. I think I had the provider/delegate switched or one was signing the wrong message. But I pushed the finalized notebook in case anyone else has an issue.

**Comment by shannonwells** [comment]
@iamianM by the way thanks for filing this issue, especially for posting your notebook.
