### ISSUE TITLE
Register a new Schema

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/mrc#28]
As a user I want to create a new schema.

Check in on #27 for schema + message format, but not blocking

## Acceptance Criteria
- [x] I should be able to call `register_schema` to register a [Thrift|Avro|TBD] schema
- [x] The schema should be assigned unique schema_id (sequential, u16)
- [x] An active node should receive the event `SchemaRegistered`
- [x] Tests
- [x] Basic Benchmarks
- [x]  Generate Spec files

**Extrinsic**: `register_schema`
Cost: MRC Token, one time fee
Parameters:
- serialized_schema: The serialized thrift schema

Emits: `SchemaRegistered`: block_number, schema_id, serialized_schema

**Assumptions**
- Zero length schemas are malformed and handled by future validation stories (#29 )
- Maximum schema is determined by the maximum size of a block + it just costs more for larger schemas (byte length pricing on extrinsic parameters)

**References**
- https://github.com/Liberty30/mrc/pull/17

**Comment by saraswatpuneet** [comment]
seialized_schema is of type Vec<u8> and will be avro serialized type
