### ISSUE TITLE
Get Schema Details

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/mrc#31]
As a user, I want to be able to get the details about a given schema id.

**Acceptance Criteria**
- [x] RPC: get_schema
  - Might be custom or built in. tbd in implementation 
  - param: schema_id
  - reutrns: schema_id, serialized_schema, created_at (block number)
- [x] Tests

**Comment by aramikm** [comment]
currently it seems like we are not storing the creation block number. I'm not sure if there is any efficient way to get it if we don't store it.

**Comment by saraswatpuneet** [comment]
@wilwade  do we need block number? if so any reasons to know? like retiring or deprecating based on block number or based on if a schema is being used or not, like a stale schema

**Comment by saraswatpuneet** [comment]
Or should we have a blocknumber in schema policy that gets updated by message store when the last message for that schema was stored, That way schema seeing no actions for N number of blocks can be marked as point of interest for possible retirement

**Comment by wilwade** [comment]
@saraswatpuneet I guess we don't need the block number. We might need the expire block for #33, but we can worry about that then.

I cannot see a reason for a created at block number at this time.
