### ISSUE TITLE
Schema Cost Calculator

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/mrc#34]
DEPENDENT: #28 

As a User, I want to know how much my schema is going to cost.

**Acceptance Criteria**
- RPC: `schema_estimator`
  - params: same as `register_schema`
  - Response: Tokens it would cost to register the schema (not counting tips)

**Comment by saraswatpuneet** [comment]
Following two issues created out of this
1. #77  - Currency, its adapters, converters etc,
2. #79 - MRC weight to fee conversion etc.
