### ISSUE TITLE
SUDO Extrensic: Set the maximum size of a schema

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/mrc#66]
DEPENDENT: #28

As governance, I should be able to adjust the maximum size of a schema.

**Acceptance Criteria**
- [ ] An extrinsic that only can be called via sudo
- [ ] Alters the MAXIMUM_SCHEMA_SIZE
- [ ] Only effects future schema, not prior schema
- [ ] Schema longer than the set size should be rejected from registration

**Comment by enddynayn** [comment]
Maybe we could consider setting the MaxWeight of the register_schema so that it fails at the transaction pool level.
